
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 3000:3000
    environment:
      - DB_NAME=posts
      - DB_CONNECTION=mongodb://vinEll:vinEllPass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/posts.js:/docker-entrypoint-initdb.d/posts.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vinEll
      - MONGO_INITDB_DATABASE=posts
      - MONGO_INITDB_ROOT_PASSWORD=vinEllPass
volumes:
  dbdata:
